
package paq_webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaCiudadanoSoap", targetNamespace = "http://ruminahui.gob.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaCiudadanoSoap {


    /**
     * 
     * @param usuario
     * @param password
     * @param cedula
     * @return
     *     returns paq_webservice.ClassCiudadania
     */
    @WebMethod(operationName = "BusquedaPorCedula", action = "http://ruminahui.gob.ec/BusquedaPorCedula")
    @WebResult(name = "BusquedaPorCedulaResult", targetNamespace = "http://ruminahui.gob.ec/")
    @RequestWrapper(localName = "BusquedaPorCedula", targetNamespace = "http://ruminahui.gob.ec/", className = "paq_webservice.BusquedaPorCedula")
    @ResponseWrapper(localName = "BusquedaPorCedulaResponse", targetNamespace = "http://ruminahui.gob.ec/", className = "paq_webservice.BusquedaPorCedulaResponse")
    public ClassCiudadania busquedaPorCedula(
        @WebParam(name = "Cedula", targetNamespace = "http://ruminahui.gob.ec/")
        String cedula,
        @WebParam(name = "Usuario", targetNamespace = "http://ruminahui.gob.ec/")
        String usuario,
        @WebParam(name = "Password", targetNamespace = "http://ruminahui.gob.ec/")
        String password);

    /**
     * 
     * @param usuario
     * @param password
     * @param cedula
     * @return
     *     returns paq_webservice.ClassCiudadania
     */
    @WebMethod(operationName = "BusquedaCedulaActual", action = "http://ruminahui.gob.ec/BusquedaCedulaActual")
    @WebResult(name = "BusquedaCedulaActualResult", targetNamespace = "http://ruminahui.gob.ec/")
    @RequestWrapper(localName = "BusquedaCedulaActual", targetNamespace = "http://ruminahui.gob.ec/", className = "paq_webservice.BusquedaCedulaActual")
    @ResponseWrapper(localName = "BusquedaCedulaActualResponse", targetNamespace = "http://ruminahui.gob.ec/", className = "paq_webservice.BusquedaCedulaActualResponse")
    public ClassCiudadania busquedaCedulaActual(
        @WebParam(name = "Cedula", targetNamespace = "http://ruminahui.gob.ec/")
        String cedula,
        @WebParam(name = "Usuario", targetNamespace = "http://ruminahui.gob.ec/")
        String usuario,
        @WebParam(name = "Password", targetNamespace = "http://ruminahui.gob.ec/")
        String password);

    /**
     * 
     * @param usuario
     * @param ruc
     * @param password
     * @return
     *     returns paq_webservice.ClassCiudadania
     */
    @WebMethod(operationName = "BusquedaPorRuc", action = "http://ruminahui.gob.ec/BusquedaPorRuc")
    @WebResult(name = "BusquedaPorRucResult", targetNamespace = "http://ruminahui.gob.ec/")
    @RequestWrapper(localName = "BusquedaPorRuc", targetNamespace = "http://ruminahui.gob.ec/", className = "paq_webservice.BusquedaPorRuc")
    @ResponseWrapper(localName = "BusquedaPorRucResponse", targetNamespace = "http://ruminahui.gob.ec/", className = "paq_webservice.BusquedaPorRucResponse")
    public ClassCiudadania busquedaPorRuc(
        @WebParam(name = "Ruc", targetNamespace = "http://ruminahui.gob.ec/")
        String ruc,
        @WebParam(name = "Usuario", targetNamespace = "http://ruminahui.gob.ec/")
        String usuario,
        @WebParam(name = "Password", targetNamespace = "http://ruminahui.gob.ec/")
        String password);

}
